env: test4
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8081
gril:
  name: lili
  age: 30
